package-lock.json, package.json, src/App.tsx, src/pages/Home.tsx, src/style/globalStyles.tsx
- root color 추가
- button, input 기본 스타일 적용
- 폰트 적용
- global style 더 추가할 건 없는지 확인 부탁 드립니다.
=> Design: Add global style

package-lock.json, package.json, src/api/api.tsx, src/api/axios.tsx, src/pages/Auth/Login.tsx, src/pages/Auth/SignUp.tsx, src/router.tsx
- form 유효성 검사를 위한 yup 라이브러리 설치
- axios.tsx content-type 수정
- 회원가입, 로그인페이지 API 연결
- 
- 생년월일 셀렉트박스 구성과 formData형식에 맞추기 위해 for문을 사용했는데, 더 깔끔하게 바꿀 수 있는 방법이 있을까요?
=> Feat: 회원가입, 로그인 페이지 API 연결

src/components/common/layout/Header.tsx, src/components/common/layout/Navigation.tsx, src/components/product/DepositsItem.tsx, src/components/product/LoansItem.tsx, src/components/product/ProductItem.tsx, src/pages/Home.tsx, src/pages/Search.tsx, src/style/globalStyles.tsx
=> Design: 검색 UI 추가

src/components/common/layout/Navigation.tsx, src/pages/Detail.tsx
=> Design: 로그아웃버튼 배치 수정

src/api/api.tsx, src/components/cart/CartPageCard.tsx, src/components/common/layout/Header.tsx, src/components/common/layout/Navigation.tsx, src/pages/Cart.tsx, src/pages/Home.tsx, src/style/globalStyles.tsx, src/utils/cookie.ts
- 토큰이 있을 경우에만 추천상품 api 요청되도록 조건문 추가
- 로그인 상태별 메인페이지 구성 변경
- 로그인 상태별 내비게이션 버튼(로그인/로그아웃)
- 장바구니 레이아웃
- 헤더 햄버거메뉴 아이콘 변경
-
=> Feat: 로그인 상태에 따른 메인페이지 구성

package-lock.json, package.json, src/api/api.tsx, src/api/axios.tsx, src/pages/Cart.tsx, src/pages/Detail.tsx
- 장바구니 배열로 저장
- react-confirm-alert 라이브러리 설치 (npm install 필요)
- axios.tsx에서 콘솔로그 코드 삭제
-
-
=> Feat: 장바구니 배열 로컬스토리지 저장

src/api/api.tsx, src/components/allProducts/DepositProductCard.tsx, src/components/allProducts/LoanProductCard.tsx, src/components/home/Main.tsx, src/components/product/ProductItem.tsx, src/pages/Auth/FindPassword.tsx, src/pages/Detail.tsx, src/pages/Home.tsx, src/router.tsx
- 상품 클릭 시 해당 상품 상세페이지 연결
- 상품데이터 들어오기 전 상태일 때 로딩애니메이션 띄우기
-
=> Feat: 상품 클릭 시 해당 상품 상세페이지 연결

src/App.tsx, src/api/api.tsx, src/components/common/AlertLoginState.tsx, src/components/common/layout/Header.tsx, src/components/common/layout/Navigation.tsx, src/components/product/ProductItem.tsx, src/components/product/SearchItem.tsx, src/pages/Home.tsx, src/pages/Recommend.tsx, src/pages/Search.tsx
- 맞춤 상품 UI / API 추가
- 검색 / product 컴포넌트 링크 수정
- 로그인 안내 페이지 간격 수정
-
=> Feat: 맞춤상품 추가 및 login 유무 token으로 재 반영

src/components/allProducts/MyProducts.tsx, src/components/allProducts/ProductsMenu.tsx, src/components/user/Setting.tsx, src/components/user/UserProfile.tsx, src/pages/Recommend.tsx, src/pages/allProducts/AllProducts.tsx
=> Feat: 마이페이지 유저 정보 추가 및 UI 수정

src/api/api.tsx, src/components/common/layout/Navigation.tsx, src/components/user/Setting.tsx, src/pages/Auth/FindPassword.tsx, src/pages/Auth/SignUp.tsx, src/pages/Detail.tsx, src/store/loginSlice.tsx, src/store/store.tsx
- 리팩토링 : API 호출 함수 로직 분리
- 로그인 상태 슬라이스 수정
-
-
=> Refactor: api 코드 리팩토링

src/api/allProductsApi.tsx, src/api/api.tsx, src/components/cart/CartPageCard.tsx, src/components/user/PurchaseCard.tsx, src/components/user/PurchaseList.tsx, src/components/wish/WishCard.tsx, src/pages/Home.tsx
- 장바구니 > 신청상품 예외처리
- 메인페이지 가입상품 개수 연결
- 주석 추가
- 불필요한 콘솔 정리
=> Feat: 신청상품 관련 api 연결

index.d.ts, src/components/cart/CartPageCard.tsx, src/components/common/layout/Navigation.tsx, src/components/user/Setting.tsx, src/pages/Auth/FindPassword.tsx, src/pages/Auth/Login.tsx, src/pages/Auth/SignUp.tsx, src/pages/Detail.tsx, src/style/globalStyles.tsx, src/utils/AlertModal.tsx
=> Design: alert, confirm 디자인 변경

src/components/common/layout/Header.tsx
- 
- 헤더 검색 기능 추가
- 추가해봤는데 이상한가요..??ㅎㅎㅎ
=> feat: 헤더 검색바 추가

src/pages/Search.tsx
=> Feat: 정렬 기능 추가

README.md, src/api/allProductsApi.tsx, src/api/api.tsx, src/components/user/PurchaseCard.tsx, src/components/user/PurchaseList.tsx, src/components/user/Setting.tsx, src/pages/allProducts/CharterLoan.tsx, src/pages/allProducts/MortgageLoan.tsx
=> Feat: 가입상품 정보 출력

src/components/allProducts/DepositProductCard.tsx, src/components/allProducts/LoanProductCard.tsx, src/components/cart/CartPageCard.tsx, src/components/product/ProductItem.tsx, src/components/product/SearchItem.tsx, src/components/user/PurchaseCard.tsx, src/components/wish/WishCard.tsx, src/pages/Home.tsx, src/pages/Search.tsx
=> Design: 카드 그림자 추가

src/api/api.tsx, src/components/user/PurchaseCard.tsx, src/components/user/PurchaseList.tsx
=> Feat: 신청취소 로직 수정

src/components/allProducts/MyProducts.tsx, src/components/user/PurchaseList.tsx
=> Design: 전체상품페이지 배경색상 수정

src/App.tsx, src/api/api.tsx, src/components/cart/CartPageCard.tsx, src/components/common/layout/Navigation.tsx, src/pages/Cart.tsx, src/pages/Detail.tsx, src/pages/Home.tsx
- 로그아웃 시 장바구니 초기화
- 상세페이지에 상품신청 기능 추가
- 내비게이션 바 메뉴 변경
- API 호출 후 alert 함수 재사용을 위해 api파일로 이동
=> Feat: 로그아웃 시 장바구니 초기화

src/pages/Purchase.tsx
- 구입 상품 페이지에서 상품신청 취소시 상품 리스트 초기화
=> Feat: 가입상품 취소시 렌더

src/components/user/PurchaseCard.tsx, src/pages/Purchase.tsx, src/pages/Wish.tsx
=> Feat: 신청상품 상태별 토글 추가

README.md, src/components/user/CertifyUser.tsx, src/components/user/EditUser.tsx, src/pages/Wish.tsx, src/pages/allProducts/AllProducts.tsx
- 회원정보 수정, 전체상품, 관심상품 텍스트 및 디자인 일부 수정
=> Design: 페이지 텍스트 및 디자인 수정

src/pages/Purchase.tsx
=> Design: 가입/취소상품 없을 경우 안내 이미지 추가

src/pages/Detail.tsx, src/utils/cookie.ts
=> Fix: 상세페이지 로그인 안내 로직 수정

src/pages/Purchase.tsx, src/pages/Wish.tsx
=> Feat: 관심상품, 가입상품 로그인 안내 추가

src/pages/Detail.tsx, src/pages/Home.tsx
- 상세페이지 텍스트 줄바꿈 방식 변경
- 메인페이지 상품추천 안내문구 추가
=> Design: 상세페이지 텍스트 줄바꿈 방식 변경

src/pages/Home.tsx
=> Feat: 메인 추천상품 3개 미만일 시 맞춤추천 api 적용
